# Generated by Django 4.2.19 on 2025-02-24 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VendorDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_code', models.CharField(max_length=50, unique=True)),
                ('vendor_name', models.CharField(max_length=100)),
                ('contact_person', models.CharField(max_length=100)),
                ('tel_no', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('lst_no', models.CharField(blank=True, max_length=50, null=True)),
                ('gst_no', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.TextField()),
            ],
        ),
    ]
