# Generated by Django 4.2.19 on 2025-02-27 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_customerdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Company Name')),
                ('lst_no', models.CharField(blank=True, max_length=100, null=True, verbose_name='LST No')),
                ('pan_no', models.CharField(blank=True, max_length=100, null=True, verbose_name='PAN No')),
                ('cst_no', models.CharField(blank=True, max_length=100, null=True, verbose_name='CST No')),
                ('company_address', models.TextField(verbose_name='Company Address')),
            ],
        ),
    ]
