# Generated by Django 4.2.19 on 2025-03-01 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0007_remove_itemdetail_active'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ItemDetail',
        ),
    ]
