# Generated by Django 4.2.20 on 2025-03-15 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('raw_material', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RmLabelGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(max_length=255)),
                ('vendor_code', models.CharField(max_length=50)),
                ('item_name', models.CharField(max_length=255)),
                ('item_code', models.CharField(max_length=50)),
                ('rm_code', models.CharField(max_length=50)),
                ('no_of_bags', models.IntegerField()),
                ('next_bag_no', models.IntegerField()),
                ('invoice_no', models.CharField(max_length=100)),
                ('invoice_date', models.DateField()),
                ('batch_no', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RmMaterialIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iss_no', models.CharField(max_length=50, unique=True)),
                ('date_of_issue', models.DateField()),
                ('issued_to_whom', models.CharField(max_length=255)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('bag_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='rawinwardmaterial',
            name='bag_type',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rawinwardmaterial',
            name='po_no',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='RmMaterialIssueSub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(max_length=50)),
                ('item_name', models.CharField(max_length=255)),
                ('uom', models.CharField(max_length=50)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_bags', models.IntegerField()),
                ('batch_no', models.CharField(max_length=100)),
                ('bags_issued', models.IntegerField()),
                ('issue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='raw_material.rmmaterialissue')),
            ],
        ),
    ]
