# Generated by Django 4.2.19 on 2025-02-27 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0004_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='InwardMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(max_length=50)),
                ('invoice_date', models.DateField()),
                ('grn_no', models.CharField(max_length=50)),
                ('grn_date', models.DateField()),
                ('received_date', models.DateField()),
                ('store', models.CharField(max_length=100)),
                ('po_date', models.DateField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('bag_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.category')),
                ('po_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.customerdetail')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.vendordetail')),
            ],
        ),
        migrations.CreateModel(
            name='RawInwardMaterialSub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(max_length=50)),
                ('item_name', models.CharField(max_length=255)),
                ('uom', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('no_of_boxes', models.IntegerField()),
                ('received_date', models.DateField()),
                ('inward_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_materials', to='master.inwardmaterial')),
            ],
        ),
    ]
