# Generated by Django 4.2.19 on 2025-03-01 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0005_inwardmaterial_rawinwardmaterialsub'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(blank=True, max_length=50, null=True)),
                ('item_name', models.CharField(blank=True, max_length=255, null=True)),
                ('rack_no', models.CharField(blank=True, max_length=50, null=True)),
                ('rol', models.IntegerField(blank=True, null=True)),
                ('rate', models.FloatField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('grade', models.CharField(blank=True, max_length=100, null=True)),
                ('hsncode', models.CharField(blank=True, max_length=50, null=True)),
                ('molqty', models.FloatField(blank=True, null=True)),
                ('packingqty', models.FloatField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
