# Generated by Django 4.2.19 on 2025-03-01 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0006_itemdetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemdetail',
            name='active',
        ),
    ]
