# Generated by Django 4.2.19 on 2025-03-03 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0009_itemdetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rawinwardmaterialsub',
            name='inward_material',
        ),
        migrations.DeleteModel(
            name='InwardMaterial',
        ),
        migrations.DeleteModel(
            name='RawInwardMaterialSub',
        ),
    ]
