# Generated by Django 5.1.7 on 2025-03-21 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255, unique=True)),
                ('category', models.CharField(choices=[('RM', 'Raw Materials'), ('PM', 'Packing Materials'), ('FG', 'Finished Goods')], default='RM', max_length=2)),
                ('inward', models.PositiveIntegerField(default=0)),
                ('outward', models.PositiveIntegerField(default=0)),
                ('balance', models.PositiveIntegerField(default=0)),
                ('order_level', models.PositiveIntegerField(default=0)),
                ('open_balance', models.PositiveIntegerField(default=0)),
                ('closing_stock', models.PositiveIntegerField(default=0)),
                ('reorder_level', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
