# Generated by Django 5.1.7 on 2025-03-20 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemdetail',
            name='uom',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
