# Generated by Django 5.1.7 on 2025-04-05 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_itemdetail_uom'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemdetail',
            name='alt_uom',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itemdetail',
            name='opening_stock',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='BillOfMaterials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(max_length=100)),
                ('item_name', models.CharField(max_length=255)),
                ('required_qty', models.FloatField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bom_entries', to='master.itemdetail')),
            ],
        ),
    ]
