# Generated by Django 5.1.7 on 2025-03-17 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PMLabelGenerationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('item_code', models.CharField(max_length=50)),
                ('noofpacks', models.IntegerField()),
                ('next_pack_no', models.IntegerField()),
                ('lot_batch_no', models.CharField(max_length=255)),
                ('packing_qty', models.IntegerField()),
                ('receipt_date', models.DateField()),
            ],
        ),
    ]
