# Generated by Django 5.1.7 on 2025-03-18 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packing_materials', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackingInwardMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_id', models.IntegerField()),
                ('invoice_no', models.CharField(max_length=50)),
                ('invoice_date', models.DateField()),
                ('vendor_code', models.CharField(max_length=100)),
                ('vendor_name', models.CharField(max_length=255)),
                ('grn_no', models.CharField(max_length=50)),
                ('grn_date', models.DateField()),
                ('recieved_date', models.DateField()),
                ('store', models.CharField(max_length=100)),
                ('po_date', models.DateField()),
                ('po_no', models.CharField(max_length=50)),
                ('bag_type', models.CharField(max_length=50)),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='pmmaterialissue',
            fields=[
                ('matIssueId', models.AutoField(primary_key=True, serialize=False)),
                ('issue_no', models.CharField(blank=True, max_length=50, unique=True)),
                ('issue_date', models.DateField(default='now')),
                ('issue_to_whom', models.CharField(max_length=100)),
                ('bag_types', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PackingInwardMaterialSub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(max_length=100)),
                ('item_name', models.CharField(max_length=255)),
                ('uom', models.CharField(max_length=100)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('no_of_bags', models.IntegerField()),
                ('recieved_date', models.DateField()),
                ('packing_material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='packing_materials.packinginwardmaterial')),
            ],
        ),
        migrations.CreateModel(
            name='pmmaterialissuesub',
            fields=[
                ('matIssueSubId', models.AutoField(primary_key=True, serialize=False)),
                ('item_code', models.CharField(max_length=100)),
                ('item_name', models.CharField(max_length=100)),
                ('uom', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('stock_qty', models.IntegerField()),
                ('total_bags', models.IntegerField()),
                ('batch_no', models.CharField(max_length=50)),
                ('bags_issued', models.IntegerField()),
                ('matIssueId', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='packing_materials.pmmaterialissue')),
            ],
        ),
    ]
