# Generated by Django 5.1.7 on 2025-03-18 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packing_materials', '0002_packinginwardmaterial_pmmaterialissue_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packinginwardmaterial',
            name='issue_id',
        ),
    ]
