# Generated by Django 5.1.7 on 2025-03-21 04:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packing_materials', '0004_purchaseorder_purchaseorderitem_uploadedfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packinginwardmaterial',
            name='grn_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='packinginwardmaterial',
            name='grn_no',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='pmmaterialissue',
            name='issue_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='pmmaterialissue',
            name='issue_no',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
