# Generated by Django 5.1.7 on 2025-03-18 11:39

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AmInwardMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(max_length=50)),
                ('invoice_date', models.DateField()),
                ('vendor_code', models.CharField(max_length=100)),
                ('vendor_name', models.CharField(max_length=255)),
                ('grn_no', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('grn_date', models.DateField(default=datetime.date.today)),
                ('store', models.CharField(max_length=100)),
                ('po_date', models.DateField()),
                ('po_no', models.CharField(max_length=50)),
                ('bag_type', models.CharField(max_length=50)),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='assetMaterialIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iss_no', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('date_of_issue', models.DateField(default=datetime.date.today)),
                ('issued_to_whom', models.CharField(max_length=255)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('bag_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='AmInwardMaterialItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(max_length=100)),
                ('item_name', models.CharField(max_length=255)),
                ('uom', models.CharField(max_length=100)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('am_inward_material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asset_management.aminwardmaterial')),
            ],
        ),
        migrations.CreateModel(
            name='assetMaterialIssueSub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(max_length=50)),
                ('item_name', models.CharField(max_length=255)),
                ('uom', models.CharField(max_length=50)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('batch_no', models.CharField(max_length=100)),
                ('issue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asset_management.assetmaterialissue')),
            ],
        ),
    ]
