# Generated by Django 4.2.20 on 2025-03-10 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RawInwardMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(max_length=50)),
                ('invoice_date', models.DateField()),
                ('vendor_code', models.CharField(max_length=100)),
                ('vendor_name', models.CharField(max_length=255)),
                ('grn_no', models.CharField(max_length=50)),
                ('grn_date', models.DateField()),
                ('store', models.CharField(max_length=100)),
                ('po_date', models.DateField()),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RawInwardMaterialSub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(max_length=100)),
                ('item_name', models.CharField(max_length=255)),
                ('uom', models.CharField(max_length=100)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('no_of_bags', models.IntegerField()),
                ('mfg_date', models.DateField()),
                ('exp_date', models.DateField()),
                ('lot_no', models.CharField(max_length=100)),
                ('repacking_batch_no', models.CharField(max_length=100)),
                ('inward_material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='raw_material.rawinwardmaterial')),
            ],
        ),
    ]
