# Generated by Django 5.1.7 on 2025-03-18 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FGInwardMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inward_no', models.CharField(max_length=50)),
                ('inward_date', models.DateField()),
                ('store', models.CharField(max_length=100)),
                ('po_date', models.DateField()),
                ('po_no', models.CharField(max_length=50)),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FGInwardMaterialSub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(max_length=100)),
                ('item_name', models.CharField(max_length=255)),
                ('uom', models.CharField(max_length=100)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('box_no', models.IntegerField()),
                ('mfg_date', models.DateField()),
                ('batch_no', models.CharField(max_length=100)),
                ('inward_material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finished_goods.fginwardmaterial')),
            ],
        ),
        migrations.CreateModel(
            name='FGLabelGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(editable=False, max_length=255)),
                ('batch_no', models.CharField(max_length=255)),
                ('packing_qty', models.IntegerField()),
                ('no_of_bags', models.IntegerField()),
                ('next_bag_no', models.CharField(max_length=255)),
                ('date_of_packing', models.DateField()),
                ('date_of_expiry', models.DateField()),
                ('item_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.itemdetail')),
            ],
        ),
        migrations.CreateModel(
            name='PackingSlip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ps_no', models.CharField(max_length=50)),
                ('ps_date', models.DateField()),
                ('po_no', models.CharField(max_length=50)),
                ('po_date', models.DateField()),
                ('mode_of_transport', models.CharField(max_length=50)),
                ('transport_form', models.CharField(max_length=50)),
                ('transfer_to_vehicle_no', models.CharField(max_length=50)),
                ('transport_name', models.CharField(max_length=50)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fg_packing_slips', to='master.customerdetail')),
            ],
        ),
        migrations.CreateModel(
            name='PackingSlipItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('uom', models.CharField(max_length=50)),
                ('box_bags', models.IntegerField()),
                ('batch_no', models.CharField(max_length=50)),
                ('qty', models.IntegerField()),
                ('bal_qty', models.IntegerField()),
                ('stock_qty', models.IntegerField()),
                ('item_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.itemdetail')),
                ('packing_slip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='finished_goods.packingslip')),
            ],
        ),
    ]
